### ISSUE TITLE
Document use of jekyll-datapage plugin

### ISSUE THREAD

**Issue by alancleary** [legumeinfo/jekyll-theme-legumeinfo#10]
It's uses the `_layout/taxon.html` file to generate taxa pages from the `_data/taxon_list.yml` file, which also needs to be documented. 

The documentation should include:
- A link to the jekyll-datapage plugin's documentation
- An explanation of how it is setup to work in the theme
- An explanation of how to override the template
- A description of the `_data/taxon_list.yml` structure
- An explanation of how to override the configuration in your own site's `_config.yml` file

**Comment by nathanweeks** [comment]
The [Development](https://github.com/legumeinfo/jekyll-theme-legumeinfo#development) section currently states:

> To set up your environment to develop the Legumeinfo Jekyll theme, run bundle install.
> 
> The theme is setup just like a normal Jekyll site! To test the theme, run bundle exec jekyll serve and open your browser at http://localhost:4000.

After this repo is cloned & gems `bundle install`'ed, an error like the following results when `jekyll serve --trace` or `jekyll build --trace` is specified:
```
/home/runner/work/jekyll-theme-legumeinfo/jekyll-theme-legumeinfo/vendor/bundle/ruby/2.7.0/gems/jekyll-datapage-generator-1.4.0/lib/jekyll-datapage-generator.rb:180:in `block in generate': undefined method `each' for nil:NilClass (NoMethodError)
```
(see [the output](https://github.com/legumeinfo/jekyll-theme-legumeinfo/runs/5493665077?check_suite_focus=true) of [this github actions workflow](https://github.com/legumeinfo/jekyll-theme-legumeinfo/blob/github-actions-build/.github/workflows/build.yml))

This appears to be caused by using the plugin without data from which to generate pages from ([jekyll-datapage-generator.rb:180](https://github.com/avillafiorita/jekyll-datapage_gen/blob/6e60a42b99f8d42d97b1fd5f3c2a71085901c544/lib/jekyll-datapage-generator.rb#L180) loops over records to generate pages from, apparently implying that no such records were read; copying _data/ from jekyll-legumeinfo into the jekyll-theme-legumeinfo git working tree quells this error).

If users are expected to bring their own _data before attempting to develop the theme, it would be helpful if the docs were updated to mention that.

Alternatively, if it's possible to include a sample _data/taxon_list.yml without breaking the use of this theme (?), that could be an option.

**Comment by nathanweeks** [comment]
> Thanks for putting this into an issue, Nathan. It looks like [I'm the one to blame](https://github.com/legumeinfo/jekyll-theme-legumeinfo/blame/main/README.md#L293) for the poor instructions. I'll swing back on this later this week. Do you have a preference for one of the solutions you proposed?

No worries! I think an end user would find it helpful to have a sample _data/taxon_list.yml, so a site can be built out-of-the-box without digging into docs. But not if that would break the usage of the theme (e.g., when used as a gem); also, I would defer to any theme conventions.

**Comment by alancleary** [comment]
> I think an end user would find it helpful to have a sample _data/taxon_list.yml, so a site can be built out-of-the-box without digging into docs. But not if that would break the usage of the theme (e.g., when used as a gem); also, I would defer to any theme conventions.

I'm not sure about theme conventions but I think providing a default/example `_data/taxon_list.yml` file makes sense. And I don't think the theme being a GEM will change anything. Just like with overriding `_include/` and `_layout/` files, when a user adds a `_data/taxon_list.yml` file to their site's code it should override the one coming from the theme.

**Comment by alancleary** [comment]
Sorry for the delay on this. I just copied the `_data/` directory from the starter site into the theme. I confirmed that adding files to the `_data/` directory in the site that's using theme theme (such as the starter site) completely overrides the ones from the theme.

Done in commit 563dcf9a29a1537d23704179560c2441818849a1. Closing.

**Comment by alancleary** [comment]
Whelp, I forgot to actually update the documentation, which is what this issue was originally about. Guess I'll reopen it...

**Comment by alancleary** [comment]
Done in commit 14f564b5780e0afe34556d43ab9b15c2f96bdc28. Closing.
