### ISSUE TITLE
Top navbar dropdown menu items have no hover response

### ISSUE THREAD

**Issue by That-Thing** [legumeinfo/jekyll-theme-legumeinfo#67]
The items in the top navbar dropdown menus have no response (change text color/background) when hovered over (except the cursor changing). 

Not a big issue, but adding that would be a nice quality of life improvement.

**Comment by alancleary** [comment]
It turns out the `uk-link-reset` class on the dropdown `<ul>` elements in the the `_includes/navbar-menu.html` and `_includes/navbar-lower-menu.html` files that override the theme in the jekyll-legumeinfo and jekyll-starter-legumeinfo repos is the cause of the issue. Simply removing the class reverts the dropdown links to their native coloring, thus restoring the proper hover behavior.

It looks like the commit that originally introduced the `uk-link-reset` class preceded these repos so it's not justified in either of their commit logs. If I remember correctly @sammyjava introduced the class because he didn't like the default grey color given to dropdown menu items. He can keep it that way in jekyll-legumeinfo if he (and others) would like but I'm going to open an issue to remove the class from the jekyll-starter-legumeinfo repo.

**Comment by sammyjava** [comment]
I hadn't noticed the lack of hover action, TBH. I'll follow what you do on the starter site, I don't care that much, and I think hover action is warranted.
